name: ci

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: fmt
        run: cargo fmt --check

      - name: build
        run: cargo build

      - name: clippy
        run: cargo clippy
        # uses: giraffate/clippy-action@v1
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   reporter: 'github-pr-review'
